export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILIUR = "FETCH_ORDER_FAILIUR";

export const FETCH_ORDER_BY_ORDER_ID = "FETCH_ITEM_BY_ORDER_ID";
export const FETCH_ORDER_BY_ORDER_ID_SUCCESS =
  "FETCH_ORDER_BY_ORDER_ID_SUCCESS";
export const FETCH_ORDER_BY_ORDER_ID_FAILIUR =
  "FETCH_ORDER_BY_ORDER_ID_FAILIUR";

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILIUR = "UPDATE_ITEM_FAILIUR";

export const FETCH_ORDER_BY_USER_REQUEST = "FETCH_ORDER_BY_USER_REQUEST";
export const FETCH_ORDER_BY_USER_SUCCESS = "FETCH_ORDER_BY_USER_SUCCESS";
export const FETCH_ORDER_BY_USER_FAILIUR = "FETCH_ORDER_BY_USER_FAILIUR";

export const ADD_ITEM_TO_ORDER_REQUEST = "ADD_ITEM_TO_ORDER_REQUEST";
export const ADD_ITEM_TO_ORDER_SUCCESS = "ADD_ITEM_TO_ORDER_SUCCESS";
export const ADD_ITEM_TO_ORDER_FAILIUR = "ADD_ITEM_TO_ORDER_FAILIUR";

export const FETCH_ITEM_TO_ORDER_REQUEST = "FETCH_ITEM_TO_ORDER_REQUEST";
export const FETCH_ITEM_TO_ORDER_SUCCESS = "FETCH_ITEM_TO_ORDER_SUCCESS";
export const FETCH_ITEM_TO_ORDER_FAILIUR = "FETCH_ITEM_TO_ORDER_FAILIUR";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILIUR = "DELETE_ITEM_FAILIUR";
